language: php
dist: xenial

before_install:
  - pip install --user cpp-coveralls

jobs:
  include:
    - stage: Test
      php: 7.3
      os:
      - windows
    - stage: Test
      php: 7.3
    - stage: Test
      php: 7.0
    - stage: Test
      php: 7.1
    - stage: Test
      php: 7.2
    - stage: Test
      php: 7.4snapshot

before_script:
  - phpize
  - ./configure
  - make all -j4
  - make install
  - echo "extension=smd5.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script:
  - make test

after_success:
  - make coveralls
